Use Object.Copy when cloning globals in Compiled
d5/tengo pull request #393
Opened 2022-09-22 12:15 UTC by ipsusila

An attempt to fix issue #336

2022-09-24 15:28 UTC, geseq requested changes

2022-09-24 15:28 UTC, geseq commented on script_test.go
> +}
I suggest simplifying the test to keep it focused

```suggestion
func TestCompiled_Clone(t *testing.T) {
	script := tengo.NewScript([]byte(`
count = count + 1
data["b"] = 2
`))

	err := script.Add("data", map[string]interface{}{"a": 1})
	require.NoError(t, err)

	err = script.Add("count", 1000)
	require.NoError(t, err)

	compiled, err := script.Compile()
	require.NoError(t, err)

	clone := compiled.Clone()
	err = clone.RunContext(context.Background())
	require.NoError(t, err)

	count := compiled.Get("count").Int()
	require.Equal(t, 1000, count)

	data := compiled.Get("data").Map()
	require.Equal(t, 1, len(data))
}
```

2022-09-24 15:29 UTC, geseq commented
@ipsusila  thanks for the PR. Let's simplify the test but otherwise good to go

2022-09-25 14:23 UTC, ipsusila commented
Thank you @geseq I'm agree with you.

2022-09-25 14:30 UTC, geseq approved these changes

2022-09-25 14:30 UTC, merged